name: meal_mate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 # ---------------------------         ----------------
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.5
  adaptive_theme: ^3.6.0
  zoom_tap_animation: ^1.1.0
  flutter_svg: ^2.0.10+1
  animated_snack_bar: ^0.4.0
  persistent_bottom_nav_bar: ^5.0.2
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0
  cached_network_image: ^3.3.1
  rename: ^3.0.2
  permission_handler: ^11.3.1
  firebase_storage: ^11.6.11
  image_picker: ^1.0.7
  google_maps_flutter: ^2.6.0
  location: ^5.0.3
  sqflite: ^2.3.2
#  google_sign_in: ^6.2.1

  # ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # ------------------- assets ---------------

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/icons/89ccd7ea-e18d-41c9-86ed-d0b08327fee4.png
    - assets/icons/9090616a-95e2-457b-ac24-1ed2c7e01c51.png
    - assets/icons/fee230f4-943c-4de9-bf03-e435b5a3bbeb.png



  fonts:
     - family: Cera Pro
       fonts:
         - asset: assets/fonts/cerapro-regular.ttf

     - family: Recoleta
       fonts:
         - asset: assets/fonts/Recoleta-RegularDEMO.otf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
