name: meal_mate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 # ---------------------------         ----------------
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.5
  adaptive_theme: ^3.6.0
  zoom_tap_animation: ^1.1.0
  flutter_svg: ^2.0.10+1
  animated_snack_bar: ^0.4.0
  persistent_bottom_nav_bar: ^5.0.2
  google_sign_in: ^6.2.1

  # ---------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # ------------------- assets ---------------

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/



  fonts:
     - family: Cera Pro
       fonts:
         - asset: assets/fonts/cerapro-regular.ttf

     - family: Recoleta
       fonts:
         - asset: assets/fonts/Recoleta-RegularDEMO.otf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
